### ISSUE TITLE
Windows 11 is detected as Windows 10

### ISSUE THREAD

**Issue by bonn2** [natanfudge/Crashy#34]
I am running windows 11 and crashy reports are showing me as windows 10.
![image](https://user-images.githubusercontent.com/42011672/157308545-49b8ae88-e7be-4830-b9c7-516b8fe12dc2.png)

**Comment by bonn2** [comment]
Don't have the original, but I updated and held f3+c and it generated another that says win10 [https://crashy.net/cfi8XbF2BLg3J7laj3V2](https://crashy.net/cfi8XbF2BLg3J7laj3V2)

**Comment by natanfudge** [comment]
> 	Operating System: Windows 10 (amd64) version 10.0
As far as Minecraft is concerned, you're using Windows 10.

**Comment by bonn2** [comment]
Well then if Minecraft apparently can't tell the difference, maybe it should be listed as Windows 10/11 since it is ambiguous.
