### ISSUE TITLE
My single player Minecraft keeps crashing when going to one area with an auto furnace setup. Only happened recently and I have used the area many times.

### ISSUE THREAD

**Issue by DSAH1997** [natanfudge/Crashy#37]
NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.save(net.minecraft.nbt.CompoundTag)'
at

FurnaceProvider.appendServerData (Line 56)

at

FurnaceProvider.appendServerData (Line 21)

at

RequestTilePacket$Handler.lambda$onMessage$0 (Line 62)

at

NetworkEvent$Context.enqueueWork (Line 208)

at

RequestTilePacket$Handler.onMessage (Line 46)

at

IndexedMessageCodec.lambda$tryDecode$3 (Line 114)

at

Optional.ifPresent (Line 178)

at

IndexedMessageCodec.tryDecode (Line 114)

at

IndexedMessageCodec.consume (Line 148)

at

SimpleChannel.networkEventListener (Line 68)

at

EventBus.doCastFilter (Line 247)

at

EventBus.lambda$addListener$11 (Line 239)

at

EventBus.post (Line 302)

at

EventBus.post (Line 283)

at

NetworkInstance.dispatch (Line 68)

at

NetworkHooks.lambda$onCustomPayload$1 (Line 75)

at

Optional.map (Line 260)

at

NetworkHooks.onCustomPayload (Line 75)

at

ServerGamePacketListenerImpl.m_7423_ (Line 1416)

at

ServerboundCustomPayloadPacket.m_5797_ (Line 35)

at

ServerboundCustomPayloadPacket.m_5797_ (Line 8)

at

PacketUtils.lambda$checkThreadAndEnqueue$0 (Line 38)

at

PacketRunnable.run (Line 28)

at

TickTask.run (Line 18)

at

BlockableEventLoop.m_6367_ (Line 193)

at

ReentrantBlockableEventLoop.m_6367_ (Line 23)

at

MinecraftServer.m_6367_ (Line 765)

at

MinecraftServer.m_6367_ (Line 161)

at

BlockableEventLoop.m_7245_ (Line 158)

at

MinecraftServer.m_129961_ (Line 748)

at

MinecraftServer.m_7245_ (Line 742)

at

BlockableEventLoop.m_18699_ (Line 135)

at

MinecraftServer.m_130012_ (Line 727)

at

MinecraftServer.m_130011_ (Line 672)

at

MinecraftServer.m_177918_ (Line 258)

at

Thread.run (Line 833)

**Comment by natanfudge** [comment]
Unrelated to crashy

**Comment by DSAH1997** [comment]
When my world crashed it showed a button to open up crashy on the menu, so I thought I would try it.

**Comment by natanfudge** [comment]
You can use crashy and send the url to the author of the crashing mod.

**Comment by DSAH1997** [comment]
Right okay, thank you.
