### ISSUE TITLE
Wrong 

### ISSUE THREAD

**Issue by Aleksizsmerti** [natanfudge/Crashy#43]
An error occurs when destroying a dark column - a column of dark stone

Unexpected error
I bet Cylons wouldn't have this problem.

IllegalArgumentException: Cannot get property EnumProperty{name=column, clazz=class com.ldtteam.domumornamentum.block.types.PillarShapeType, values=[PILLAR_BASE, PILLAR_CAPITAL, PILLAR_COLUMN, FULL_PILLAR]} as it does not exist in Block{minecraft:air}
at StateHolder.m_61143_ (Line 98)

at PillarBlock.onDestroyedByPlayer (Line 173)

at IForgeBlockState.onDestroyedByPlayer (Line 124)

at MultiPlayerGameMode.m_105267_ (Line 121)

at MultiPlayerGameMode.m_105283_ (Line 221)

at Minecraft.m_91386_ (Line 1466)

at Minecraft.m_91279_ (Line 1863)

at Minecraft.m_91398_ (Line 1668)

at Minecraft.m_91383_ (Line 1019)

at Minecraft.m_91374_ (Line 663)

at InGameCatcher.handleClientCrash (Line 37)

at Minecraft.modify$bbo000$atTheEndOfSecondCatchBeforePrintingCrashReport (Line 8415)

at Minecraft.m_91374_ (Line 688)

at Main.main (Line 205)

at NativeMethodAccessorImpl.invoke0 (Native Method)

at NativeMethodAccessorImpl.invoke (Line 77)

at DelegatingMethodAccessorImpl.invoke (Line 43)

at Method.invoke (Line 568)

at CommonClientLaunchHandler.lambda$launchService$0 (Line 31)

at LaunchServiceHandlerDecorator.launch (Line 37)

at LaunchServiceHandler.launch (Line 53)

at LaunchServiceHandler.launch (Line 71)

at Launcher.run (Line 106)

at Launcher.main (Line 77)

at BootstrapLaunchConsumer.accept (Line 26)

at BootstrapLaunchConsumer.accept (Line 23)

at BootstrapLauncher.main (Line 149)

**Comment by Aleksizsmerti** [comment]
Mods :
Absent By Design Mod 1.18.2-1.6.2 (absentbydesign)
Advanced Peripherals 0.7.15b (advancedperipherals)
Advancement Plaques 1.4.3 (advancementplaques)
AI-Improvements 0.5.0 (aiimprovements)
Akashic Tome 1.5-20 (akashictome)
Alex's Mobs 1.18.3 (alexsmobs)
AppleSkin 2.4.0+mc1.18 (appleskin)
Applied Botanics 1.0.1 (appbot)
Applied Energistics 2 11.0.0 (ae2)
Applied Mekanistics 1.2.0 (appmek)
Architectury 4.4.68 (architectury)
Ars Nouveau 2.4.2 (ars_nouveau)
Artifacts 1.18.2-4.1.0 (artifacts)
AttributeFix 14.0.2 (attributefix)
AutoRegLib 1.7-53 (autoreglib)
Bad Wither No Cookie Reloaded 3.13.21 (bwncr)
Balm 3.0.3+0 (balm)
Bedspreads 1.18.1-5.1.0.5 (bedspreads)
Better Compatibility Checker 1.1.14-build.26+mc1. (bcc)
Blue Skies 1.3.12 (blue_skies)
Bookshelf 13.0.13 (bookshelf)
Botania 1.18.2-432 (botania)
Buddycards Core 1.18.2-3.0.8 (buddycards)
Caelus API 1.18.1-3.0.0.2 (caelus)
Carry On 1.17.0.8 (carryon)
CC: Tweaked 1.100.5 (computercraft)
Chalk 1.2.1 (chalk)
Champions 1.18.2-2.1.5.4 (champions)
Chisels & bits 1.2.88 (chiselsandbits)
Chunk Animator 1.18.2-1.3.4 (chunkanimator)
Chunk Loaders 1.1.12 (chunkloaders)
Citadel 1.11.3 (citadel)
clickadv mod 1.18.2-2.5 (clickadv)
Client Tweaks 7.1.0 (clienttweaks)
Cloth Config v4 API 6.2.62 (cloth_config)
Clumps 8.0.0+8 (clumps)
Collective 4.25 (collective)
CommonCapabilities 2.8.2 (commoncapabilities)
Companion 2.1.0 (companion)
ConnectedTexturesMod 1.18.2-1.1.4+4 (ctm)
Connectivity Mod 1.18.2-2.9 (connectivity)
CosmeticArmorReworked 1.18.2-v2 (cosmeticarmorreworked)
CraftingTweaks 14.0.2 (craftingtweaks)
Create 0.4.1 (create)
CreativeCore 2.6.9 (creativecore)
Creeper Overhaul 1.3.0 (creeperoverhaul)
Curio of Undying 1.18-5.3.0.0 (curioofundying)
Curios API 1.18.2-5.0.7.0 (curios)
Curious Armor Stands 1.18.1-4.0.0 (curious_armor_stands)
Curious Elytra 1.18.1-5.0.1.0 (curiouselytra)
Cyclops Core 1.13.7 (cyclopscore)
DarkUtilities 10.0.4 (darkutils)
Despawning Eggs Hatch 2.4 (despawningeggshatch)
Domestication Innovation 1.4.1 (domesticationinnovation)
Domum Ornamentum 1.18.2-1.0.50-ALPHA (domum_ornamentum)
dragonfight mod 1.18.2-2.1 (dragonfight)
Druidcraft Regrown 0.0.12 (druidcraftrg)
Dusk Mod 1.18.2-1.9 (dusk)
Ecologics 1.6.8 (ecologics)
Effortless Building 1.18-2.34 (effortlessbuilding)
Engineer's Decor 1.1.22 (engineersdecor)
Enlightened End 1.1.0 (nourished_end)
ExpandAbility 6.0.0 (expandability)
Extended Lights 4.4 (extlights)
FancyMenu 2.7.2 (fancymenu)
Farmer's Delight 1.18.2-1.1.1 (farmersdelight)
Farmer's Respite 1.18.1-1.2.0 (farmersrespite)
Fast Workbench 6.0.2 (fastbench)
FastFurnace 6.0.3 (fastfurnace)
FastLeafDecay 28 (fastleafdecay)
Ferrite Core 0.0NONE (ferritecore)
Flywheel 1.18-0.6.2 (flywheel)
Forbidden & Arcanus 1.18.2-2.1.0-beta1 (forbidden_arcanus)
Forge 40.1.31 (forge)
FramedBlocks 5.2.0 (framedblocks)
Functional Storage 1.18.2-0.0.15 (functionalstorage)
GeckoLib 3.0.18 (geckolib3)
Goblin Traders 1.7.2 (goblintraders)
Guard Villagers 1.4.2 (guardvillagers)
Hunter Illager 1.18.2-4.0.1 (hunterillager)
Iceberg 1.0.44 (iceberg)
Immersive Engineering 1.18.2-8.0.1-147 (immersiveengineering)
Immersive Weathering 1.18.2-1.2.10 (immersive_weathering)
IntegratedCrafting 1.0.23 (integratedcrafting)
IntegratedDynamics 1.10.18 (integrateddynamics)
IntegratedREST 1.1.5 (integratedrest)
IntegratedTerminals 1.2.16 (integratedterminals)
IntegratedTunnels 1.8.11 (integratedtunnels)
ItemPhysic 1.6.0 (itemphysic)
Just Enough Effect Description 1.18.2-1.10 (jeed)
Just Enough Items 9.7.0.195 (jei)
Just Enough Professions (JEP) 1.2.2 (justenoughprofessions)
Just Enough Resources 0.14.1.170 (jeresources)
Kiwi 6.1.0 (kiwi)
KleeSlabs 11.1.0 (kleeslabs)
Konkrete 1.3.3 (konkrete)
KubeJS 1802.5.3-build.463 (kubejs)
KubeJS Create 1802.2.2-build.23 (kubejs_create)
KubeJS Immersive Engineering 1802.2.1-build.35 (kubejs_immersive_engineering)
KubeJS Mekanism 1802.1.3-build.8 (kubejs_mekanism)
LazyDFU 0.1.3 (lazydfu)
Little Contraptions 1.18.2.0-beta.3 (littlecontraptions)
Little Logistics 1.2.3 (littlelogistics)
Logprot 1.4 (logprot)
LootJS 2.3.0 (lootjs)
Malum 1.18.2-1.3.6 (malum)
Mantle 1.9.20 (mantle)
Markdown Manual 1.2.1 (markdown_manual)
McJtyLib 1.18-6.0.13 (mcjtylib)
Mekanism 10.2.2 (mekanism)
Mekanism: Additions 10.2.2 (mekanismadditions)
Mekanism: Generators 10.2.2 (mekanismgenerators)
Mekanism: Tools 10.2.2 (mekanismtools)
MineColonies 1.18.2-1.0.780-ALPHA (minecolonies)
Minecraft 1.18.2 (minecraft)
More Minecarts 1.4.5 (moreminecarts)
Mouse Tweaks 2.21 (mousetweaks)
Multi-Piston 1.18.2-1.2.7-ALPHA (multipiston)
Nature's Compass 1.18.2-1.9.5-forge (naturescompass)
Neon Craft 2 2.2 (neoncraft2)
Not Enough Crashes 4.1.4+1.18.2 (notenoughcrashes)
Oh The Biomes You'll Go 1.4 (byg)
OpenComputers II 0.1.7 (oc2)
Ortus Lib 1.18.2-1.0 (ortus)
Overweight Farming 1.18.2-1.3.2-forge (overweight_farming)
Paintings ++ 9.1.2.1 (paintings)
Patchouli 0.0NONE (patchouli)
PigPen 8.0.1 (pigpen)
Placebo 6.4.0 (placebo)
PneumaticCraft: Repressurized 1.18.2-3.2.3-84 (pneumaticcraft)
Polymorph 1.18.2-0.44 (polymorph)
Pop! 1.0.0 (pop)
Quark 3.2-357 (quark)
Quark Oddities 1.18 (quarkoddities)
Reap Mod 1.18.2-1.0.0 (reap)
Refined Storage 1.10.2 (refinedstorage)
Refined Storage Addons 0.8.2 (refinedstorageaddons)
RFToolsBase 1.18-3.0.7 (rftoolsbase)
RFToolsBuilder 1.18-4.0.10 (rftoolsbuilder)
RFToolsControl 1.18-5.0.5 (rftoolscontrol)
RFToolsDimensions 1.18-8.0.5 (rftoolsdim)
RFToolsPower 1.18-4.0.5 (rftoolspower)
RFToolsStorage 1.18-3.0.8 (rftoolsstorage)
RFToolsUtility 1.18-4.0.15 (rftoolsutility)
Rhino 1802.1.13-build.175 (rhino)
Roots Classic 1.18.2-1.1.23 (rootsclassic)
Runelic 11.0.1 (runelic)
Sedna for Minecraft 1.0.13 (sedna)
Selene 1.18.2-1.16.6 (selene)
ServerConfig Updater 2.0 (serverconfigupdater)
Simple Backups 1.18.2-1.1.8 (simplebackups)
Simple RPC 3.0.1 (simplerpc)
Smarter Farmers 1.18.2-1.5.0 (smarterfarmers)
Smoothchunk mod 1.18.2-1.9 (smoothchunk)
Snow Under Trees 1.2.1 (snowundertrees)
Snow! Real Magic! 4.1.0 (snowrealmagic)
Snuffles 1.0.2 (snuffles)
Sophisticated Backpacks 1.18.2-3.17.2.588 (sophisticatedbackpacks)
Sophisticated Core 1.18.2-0.2.5.28 (sophisticatedcore)
spark 1.9.1 (spark)
Sprout 1.3.1 (sprout)
Structure Gel API 2.3.0 (structure_gel)
Structurize 1.18.2-1.0.399-RELEA (structurize)
SuperMartijn642's Config Lib 1.0.9 (supermartijn642configlib)
SuperMartijn642's Core Lib 1.0.18 (supermartijn642corelib)
Supplementaries 1.18.2-1.4.0 (supplementaries)
TerraBlender 1.18.2-1.1.0.101 (terrablender)
The Conjurer 1.1.1 (conjurer_illager)
The Twilight Forest 4.1.1052 (twilightforest)
The Undergarden 0.7.1 (undergarden)
Tinkers' Construct 3.5.0.17 (tconstruct)
Titanium 3.5.3 (titanium)
TLSkinCape 1.25 (tlskincape)
TrashSlot 11.0.2 (trashslot)
Twigs 1.1.4-patch1+1.18.2 (twigs)
UI Library Mod 1.18.2-0.0.47-ALPHA (blockui)
Valhelsia Core 1.18.2-0.3.1 (valhelsia_core)
Valhelsia Structures 1.18.2-0.1.0 (valhelsia_structures)
Valhelsia Tweaks 1.18.2-0.1.0 (valhelsia_tweaks)
Waystones 10.0.0 (waystones)
Xaero's Minimap 22.8.2 (xaerominimap)
Xaero's World Map 1.22.0 (xaeroworldmap)
Xerca's Music Maker Mod 1.18.2-1.0.0 (xercamusic)
XNet 1.18-4.0.5 (xnet)
YUNG's API 1.18.2-Forge-2.0.8 (yungsapi)
YUNG's Better Dungeons 1.18.2-Forge-2.1.0 (betterdungeons)
YUNG's Better Strongholds 1.18.2-Forge-2.1.1 (betterstrongholds)

**Comment by natanfudge** [comment]
This is not a support forum.
