### ISSUE TITLE
Minecraft crashed

### ISSUE THREAD

**Issue by Fluffylu** [natanfudge/Crashy#54]
IncompatibleClassChangeError: Found interface vazkii.patchouli.common.base.PatchouliConfig$ConfigAccess, but class was expected
at

PatchouliTooltipEvent.onTooltip (Line 70)

at

ClientEvents.TooltipEvent (Line 14)

at

__ClientEvents_TooltipEvent_Pre.invoke (Native Method)

at

ASMEventHandler.invoke (Line 73)

at

EventBus.post (Line 315)

at

EventBus.post (Line 296)

at

ForgeHooksClient.onRenderTooltipPre (Line 1016)

at

Screen.m_169383_ (Line 232)

at

Screen.m_169388_ (Line 189)

at

Screen.m_6057_ (Line 170)

at

AbstractContainerScreen.m_7025_ (Line 173)

at

ContainerScreen.m_6305_ (Line 32)

at

ForgeHooksClient.drawScreenInternal (Line 440)

at

ForgeHooksClient.drawScreen (Line 433)

at

GameRenderer.m_109093_ (Line 896)

at

Minecraft.m_91383_ (Line 1115)

at

Minecraft.m_91374_ (Line 700)

at

InGameCatcher.handleClientCrash (Line 37)

at

Minecraft.modify$ckd000$atTheEndOfFirstCatchBeforePrintingCrashReport (Line 11963)

at

Minecraft.m_91374_ (Line 720)

at

InGameCatcher.handleClientCrash (Line 37)

at

Minecraft.modify$ckd000$atTheEndOfFirstCatchBeforePrintingCrashReport (Line 11963)

at

Minecraft.m_91374_ (Line 720)

at

InGameCatcher.handleClientCrash (Line 37)

at

Minecraft.modify$ckd000$atTheEndOfFirstCatchBeforePrintingCrashReport (Line 11963)

at

Minecraft.m_91374_ (Line 720)

at

Main.m_239872_ (Line 212)

at

Main.main (Line 51)

at

NativeMethodAccessorImpl.invoke0 (Native Method)

at

NativeMethodAccessorImpl.invoke (Line 77)

at

DelegatingMethodAccessorImpl.invoke (Line 43)

at

Method.invoke (Line 568)

at

CommonClientLaunchHandler.lambda$launchService$0 (Line 27)

at

LaunchServiceHandlerDecorator.launch (Line 30)

at

LaunchServiceHandler.launch (Line 53)

at

LaunchServiceHandler.launch (Line 71)

at

Launcher.run (Line 106)

at

Launcher.main (Line 77)

at

BootstrapLaunchConsumer.accept (Line 26)

at

BootstrapLaunchConsumer.accept (Line 23)

at

BootstrapLauncher.main (Line 141)

**Comment by natanfudge** [comment]
This is not a support forum
