### ISSUE TITLE
Several UI improvement requests

### ISSUE THREAD

**Issue by LambdAurora** [natanfudge/Crashy#56]
Hi, I'm a modder, and I sometimes have to deal with crashy links of crash reports.

And here's some stuff that I wish were changed because it's making my job harder:

 - [ ] Raw crash reports currently use the `font-family`: `"Roboto", "Helvetica", "Arial", sans-serif`, which is terrible! Please change to `font-family: ui-monospace, monospace`. I'm also finding it bizarre that it's not using a `<pre>` tag and instead uses a paragraph.
 - [ ] Please refrain from using `<button>` for anything that's supposed to be a link and use `<a>` instead: this is important because `<a>` let the browser provide proper context menus (especially to open said link in a new tab).
 - [ ] In the table view of System details, please replace new lines with `<br>`s, as currently loaded mods list are unreadable there.
 - [ ] I can understand to limit the amount of information shown at once, but I would really appreciate the ability to just scroll down and see the rest of the crash report instead of having to click the tabs.

**Comment by natanfudge** [comment]
Hey, these look like really great tips. Crashy is undergoing a major refactor currently to fix some stuff that is unfixable with the current implementation, so expect any changes to come in a few months at the very least.

**Comment by natanfudge** [comment]
1. Raw crash reports are now handled by the browser.
2. The 2 links use <a> now
3. I'm not actually sure what you mean, do you have an example?
4. Do you mean the `caused by:` chain?

**Comment by natanfudge** [comment]
I consider this resolved
