### ISSUE TITLE
Not Reporting System Correctly.

### ISSUE THREAD

**Issue by ClaudiusMinimus** [natanfudge/Crashy#84]
The crashy graphical report and the actual crash report do not match in this case.
The report shows:
![image](https://github.com/natanfudge/Crashy/assets/17887664/cd754864-046a-472e-b53c-3f538a97cc7b)
Whereas the crash report shows my actual configuration:
```	
Minecraft Version: 1.19.2
Operating System: Linux (amd64) version 5.4.0-148-generic
Java Version: 17.0.5, Azul Systems, Inc.
Fabric Loader 0.14.19
```
Screenshot of https://crashy.net/f3c5837f-7eed-49cd-a4fa-3a7b5bdc2afc
![image](https://github.com/natanfudge/Crashy/assets/17887664/85bcddbe-4ca6-4f93-bf8d-9fe185350ce0)

**Comment by natanfudge** [comment]
Well written issue, thanks for reporting.

**Comment by natanfudge** [comment]
Fixed.
