### ISSUE TITLE
Same crash report regardless of inputted report

### ISSUE THREAD

**Issue by Mintmane** [natanfudge/Crashy#86]
I tried to use Crashy a few minutes ago and found that the report it gave me was wildly different from the one I gave it. Wrong minecraft version, wrong mod loader, wrong date, wrong error, wrong modlist. I tried putting in a different crash report and got the exact same result.
Two different crash reports I tried pasting:
[crash-2023-05-25_09.53.35-client.txt](https://github.com/natanfudge/Crashy/files/11566360/crash-2023-05-25_09.53.35-client.txt)
[crash-2023-05-24_22.38.03-fml.txt](https://github.com/natanfudge/Crashy/files/11566361/crash-2023-05-24_22.38.03-fml.txt)
And the stuff I got both times:
![image](https://github.com/natanfudge/Crashy/assets/41555629/4ba3a8b8-d5fd-4197-abae-f7b73459ef27)
![image](https://github.com/natanfudge/Crashy/assets/41555629/7149893d-028f-4dc4-b379-ef9e71a99fae)
![image](https://github.com/natanfudge/Crashy/assets/41555629/ce122e99-6bf1-4227-b195-86bc18445dcd)

**Comment by natanfudge** [comment]
Hey, thanks for reporting. Could you link to the Crashy urls that you say have the wrong content?

**Comment by natanfudge** [comment]
This is fixed now.
